# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('ma_bai', models.AutoField(primary_key=True, serialize=False)),
                ('ten_bai', models.CharField(max_length=50)),
                ('noi_dung', models.TextField()),
                ('tong_so_view', models.IntegerField(default=0)),
                ('tong_so_binh_luan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('ma_binh_luan', models.AutoField(primary_key=True, serialize=False)),
                ('noi_dung', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenNganh',
            fields=[
                ('ma_chuyen_nganh', models.AutoField(primary_key=True, serialize=False)),
                ('ten_chuyen_nganh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DangKi',
            fields=[
                ('ma_dang_ki', models.AutoField(primary_key=True, serialize=False)),
                ('trang_thai', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('ma_khoa_hoc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khoa_hoc', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
                ('gioi_thieu', models.TextField()),
                ('chuyen_nganh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.ChuyenNganh')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiUser',
            fields=[
                ('ma_loai', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TuongTac',
            fields=[
                ('ma_tuong_tac', models.AutoField(primary_key=True, serialize=False)),
                ('so_view', models.IntegerField(default=0)),
                ('so_binh_luan', models.IntegerField(default=0)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.BaiViet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=50)),
                ('mat_khau', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=250)),
                ('gioi_tinh', models.CharField(max_length=3)),
                ('dia_chi', models.CharField(max_length=250)),
                ('loai_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.LoaiUser')),
            ],
        ),
        migrations.AddField(
            model_name='tuongtac',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.User'),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.User'),
        ),
        migrations.AddField(
            model_name='dangki',
            name='khoa_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.KhoaHoc'),
        ),
        migrations.AddField(
            model_name='dangki',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.User'),
        ),
        migrations.AddField(
            model_name='binhluan',
            name='tuong_tac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.TuongTac'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='khoa_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.KhoaHoc'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdh.User'),
        ),
    ]
