# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 08:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='noi_dung',
            field=ckeditor.fields.RichTextField(verbose_name='Soạn thảo theo cách của riêng bạn'),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='gioi_thieu',
            field=ckeditor.fields.RichTextField(verbose_name='Soạn thảo theo cách của riêng bạn'),
        ),
    ]
