# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0003_auto_20171022_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoahoc',
            name='le_phi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
