# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0005_auto_20171023_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoahoc',
            name='gioi_thieu',
            field=models.TextField(max_length=5000),
        ),
    ]
