# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0006_auto_20171023_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='trang_thai',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
