# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0009_auto_20171028_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoahoc',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
