# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdh', '0010_auto_20171028_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoahoc',
            name='gioi_thieu',
            field=models.TextField(),
        ),
    ]
